CREATE TABLE IF NOT EXISTS USERS (user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
login varchar NOT NULL,
user_name varchar,
email varchar NOT NULL UNIQUE,
birthday date NOT NULL);

CREATE TABLE IF NOT EXISTS mpa_rates (
    mpa_rate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_rate_name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films (film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
film_name varchar NOT NULL UNIQUE,
description varchar(200) NOT NULL,
release_date date NOT NULL,
duration INTEGER,
mpa_rate_id INTEGER REFERENCES mpa_rates (mpa_rate_id));

CREATE TABLE IF NOT EXISTS films_likes (
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id identity PRIMARY KEY,
    genre_name varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres (genre_id) ON DELETE CASCADE ,
        CONSTRAINT FILM_GENRE_PK
            PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friendships (
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE
);



